---

- name: Set root password post-deployment
  hosts: new_3cx_vm
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Check the Connectivity
      ansible.builtin.ping:

    - name: Update root password
      ansible.builtin.user:
        name: "{{ VM_Username }}"
        password: "{{ '{{ VM_Password }}' | password_hash('sha512') }}"
        update_password: always
      register: user_result
      until: user_result is changed
      retries: 10
      delay: 5

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./key/ansible.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0644'
